name: systemrepair
description: do an he thong
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  get: ^4.6.5
  pull_to_refresh: ^2.0.0
  loading_overlay_pro: ^2.1.1
  font_awesome_flutter: ^10.5.0
  firebase_auth: ^4.0.2
  firebase_core: ^2.15.0
  firebase_database: ^10.0.2
  firebase_messaging: ^14.2.1
  firebase_remote_config: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

